name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Installer les dépendances
        run: npm install
      
      - name: Vérifier le code (ESLint)
        run: npm run lint

      - name: Lancer les tests
        env:
          TURSO_DATABASE_URL: file:./test.db
          JWT_SECRET: 3cac36ad1aabd47c923bd7bad1995a2955efe03154b486f08ad3f5826a7717fd
        run: npm test